// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsApp22.db;

namespace SoftwareInterface.Migrations
{
    [DbContext(typeof(bakeryContext))]
    [Migration("20221222185642_order")]
    partial class order
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SoftwareInterface.Orrder", b =>
                {
                    b.Property<string>("city")
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cardnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Paymentmethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Totalamount")
                        .HasColumnType("INTEGER");

                    b.HasKey("city");

                    b.ToTable("Orrders");
                });

            modelBuilder.Entity("SoftwareInterface.User", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SoftwareInterface.feedback", b =>
                {
                    b.Property<string>("orderID")
                        .HasColumnType("TEXT");

                    b.Property<int>("rate")
                        .HasColumnType("INTEGER");

                    b.HasKey("orderID");

                    b.ToTable("feedbacks");
                });

            modelBuilder.Entity("SoftwareInterface.item", b =>
                {
                    b.Property<string>("IDcategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDcategory");

                    b.ToTable("items");
                });

            modelBuilder.Entity("WinFormsApp22.db.Account", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Confirmpassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("email");

                    b.ToTable("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
